
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://172.22.0.2:5432/aula}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234567}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
        lob:
          non_contextual_creation: true

      ddl-auto: none