spring:
  profiles:
    active: ${APP_PROFILE:test}


security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

logging:
  level:
    org:
      springframework: INFO


cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000, http://localhost:8080}